<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get admin users only
        $adminUsers = User::where('role', 'admin')->get();
        $categories = Category::whereNotNull('parent_id')->get();

        if ($adminUsers->isEmpty()) {
            $this->command->warn('No admin users found! Please run UserSeeder first!');
            return;
        }

        if ($categories->isEmpty()) {
            $this->command->warn('No subcategories found! Please run CategorySeeder first!');
            return;
        }

        $articles = [
            [
                'title' => 'Complete Guide to Adopting Your First Dog',
                'content' => "Adopting a dog is a life-changing decision that brings immense joy and responsibility. Before bringing your new furry friend home, it's essential to prepare your living space, gather necessary supplies, and understand the commitment involved.\n\nFirst, ensure your home is dog-proofed. Remove any toxic plants, secure loose wires, and create a safe space for your new pet. You'll need basic supplies including food and water bowls, a comfortable bed, collar and leash, ID tags, and appropriate food.\n\nConsider your lifestyle when choosing a dog. Active individuals might prefer energetic breeds, while those with a calmer lifestyle might opt for more relaxed companions. Remember that all dogs need regular exercise, training, and veterinary care.\n\nThe first few weeks are crucial for bonding. Establish a routine for feeding, walks, and playtime. Be patient as your dog adjusts to their new environment. Positive reinforcement training works best for building trust and teaching good behavior.\n\nRegular veterinary check-ups are essential. Ensure your dog is up-to-date on vaccinations, spayed or neutered, and receives preventive care for parasites. A healthy dog is a happy dog!\n\nRemember, adopting a dog is a long-term commitment that can last 10-15 years or more. With proper care, training, and lots of love, your adopted dog will become a cherished family member.",
                'category' => 'Dogs',
            ],
            [
                'title' => 'Understanding Cat Behavior: A Beginner\'s Guide',
                'content' => "Cats are fascinating creatures with unique behaviors that often puzzle new cat owners. Understanding your cat's body language and vocalizations is key to building a strong bond.\n\nTail position is one of the most telling signs of a cat's mood. A tail held high indicates confidence and happiness, while a puffed-up tail signals fear or aggression. A slowly swishing tail might mean your cat is focused or slightly annoyed.\n\nPurring usually indicates contentment, but cats also purr when stressed or in pain. Pay attention to the context. Meowing is primarily used to communicate with humans, not other cats. Each cat develops their own vocabulary with their owner.\n\nCats are naturally curious and need mental stimulation. Provide scratching posts, climbing structures, and interactive toys. Window perches allow them to watch the outside world, which many cats find entertaining.\n\nLitter box issues often stem from stress, medical problems, or dissatisfaction with the box's cleanliness or location. Keep the litter box clean and in a quiet, accessible area.\n\nRespect your cat's need for personal space. Unlike dogs, cats often prefer to initiate interaction. Let them come to you, and you'll build trust over time. With patience and understanding, you'll develop a deep bond with your feline friend.",
                'category' => 'Cats',
            ],
            [
                'title' => 'Essential Vaccinations for Your Pet',
                'content' => "Vaccinations are crucial for protecting your pet from serious diseases. Understanding which vaccines your pet needs and when they need them is an important part of responsible pet ownership.\n\nFor dogs, core vaccines include rabies, distemper, parvovirus, and adenovirus. Puppies typically receive their first vaccines at 6-8 weeks of age, with boosters every 3-4 weeks until they're 16 weeks old. Adult dogs need regular boosters, usually every 1-3 years depending on the vaccine.\n\nCats require vaccines for rabies, feline distemper (panleukopenia), feline herpesvirus, and calicivirus. Kittens follow a similar schedule to puppies, starting at 6-8 weeks with boosters until 16 weeks of age.\n\nNon-core vaccines are recommended based on your pet's lifestyle and risk factors. For dogs, these might include Bordetella (kennel cough), Lyme disease, and leptospirosis. For cats, feline leukemia vaccine is important for outdoor cats or those living with infected cats.\n\nVaccine reactions are rare but can occur. Watch for signs like swelling at the injection site, fever, or lethargy. Contact your veterinarian if you notice any concerning symptoms.\n\nKeep a record of your pet's vaccinations. Many boarding facilities, groomers, and dog parks require proof of current vaccinations. Regular veterinary check-ups ensure your pet stays protected throughout their life.",
                'category' => 'General',
            ],
            [
                'title' => 'Creating a Pet-Friendly Home Environment',
                'content' => "Making your home safe and comfortable for your pet is essential for their well-being and your peace of mind. A pet-friendly home considers both safety and enrichment.\n\nStart by identifying potential hazards. Secure electrical cords, remove toxic plants, and store cleaning supplies and medications out of reach. Common household items like chocolate, grapes, and certain houseplants can be toxic to pets.\n\nCreate designated spaces for your pet. A comfortable bed in a quiet corner provides a safe retreat. For cats, vertical space is important – consider cat trees or wall-mounted shelves. Dogs appreciate having their own space too, whether it's a crate or a cozy corner.\n\nPet-proof your furniture and floors. Washable slipcovers protect furniture from fur and accidents. Choose flooring that's easy to clean and provides good traction. Area rugs can help on slippery surfaces.\n\nProvide appropriate toys and enrichment. Rotate toys to keep them interesting. Puzzle feeders and interactive toys provide mental stimulation. For cats, scratching posts are essential to protect your furniture.\n\nEstablish feeding and bathroom areas. Keep food and water bowls in a consistent location. For cats, place litter boxes in quiet, accessible areas – one per cat plus one extra is the general rule.\n\nConsider your pet's needs as they age. Older pets may need ramps or steps to access favorite spots. Orthopedic beds can help with joint pain. A pet-friendly home adapts to your companion's changing needs throughout their life.",
                'category' => 'General',
            ],
            [
                'title' => 'The Benefits of Adopting Senior Pets',
                'content' => "Senior pets often get overlooked in shelters, but they make wonderful companions. Adopting an older pet comes with unique advantages that many people don't consider.\n\nSenior pets typically have calmer temperaments. They're past the energetic puppy or kitten stage and are often content with moderate exercise and lots of cuddles. This makes them ideal for people with less active lifestyles or those who work long hours.\n\nWhat you see is what you get with senior pets. Their personality is fully developed, so there are no surprises about their adult size or temperament. This makes it easier to find a pet that matches your lifestyle and living situation.\n\nMany senior pets are already trained. They often know basic commands, are house-trained, and have experience living in a home. This means less time spent on training and more time enjoying your new companion.\n\nSenior pets are grateful. Many seem to understand they've been given a second chance and form deep bonds with their adopters. The love and loyalty of a senior pet is truly special.\n\nWhile senior pets may have health considerations, many are healthy and active. Regular veterinary care can help manage any age-related issues. The years you have together, though perhaps fewer than with a younger pet, are filled with love and companionship.\n\nAdopting a senior pet is a compassionate choice that saves a life. You're giving a deserving animal a comfortable, loving home for their golden years. The bond you'll form is incredibly rewarding.",
                'category' => 'General',
            ],
            [
                'title' => 'Nutrition Guide: Feeding Your Pet Right',
                'content' => "Proper nutrition is fundamental to your pet's health and longevity. Understanding your pet's nutritional needs helps you make informed decisions about their diet.\n\nPets need a balanced diet with the right proportions of protein, fats, carbohydrates, vitamins, and minerals. The specific requirements vary by species, age, size, and activity level. Puppies and kittens need more calories and nutrients for growth, while senior pets may need fewer calories but more joint support.\n\nChoose high-quality pet food from reputable brands. Look for foods where meat is the first ingredient. Avoid foods with excessive fillers, artificial colors, or preservatives. Read labels carefully and consult your veterinarian about the best choice for your pet.\n\nPortion control is crucial. Obesity is a growing problem in pets and can lead to serious health issues. Follow feeding guidelines on pet food packages, but adjust based on your pet's individual needs and activity level. Regular weigh-ins help monitor your pet's condition.\n\nTreats should make up no more than 10% of your pet's daily calories. Choose healthy options like small pieces of cooked chicken or vegetables (for dogs). Avoid giving human food that can be toxic to pets.\n\nFresh water should always be available. Change water daily and clean bowls regularly to prevent bacterial growth.\n\nSpecial diets may be necessary for pets with health conditions. Your veterinarian can recommend prescription diets for issues like kidney disease, allergies, or digestive problems. Never change your pet's diet suddenly – transition gradually over 7-10 days to avoid digestive upset.",
                'category' => 'Dogs',
            ],
            [
                'title' => 'Training Tips for New Pet Owners',
                'content' => "Training is essential for a harmonious relationship with your pet. Whether you've adopted a puppy, kitten, or adult pet, consistent training creates a well-behaved companion.\n\nStart with basic commands. For dogs, focus on sit, stay, come, and down. Use positive reinforcement – reward desired behaviors with treats, praise, or play. Never use punishment or harsh corrections, as these can damage trust and create fear.\n\nConsistency is key. Everyone in the household should use the same commands and rules. If one person allows the dog on the couch while another doesn't, your pet will be confused.\n\nKeep training sessions short and fun. Five to ten minutes several times a day is more effective than one long session. End on a positive note to keep your pet engaged and eager for the next session.\n\nSocialization is crucial, especially for puppies and kittens. Expose them to different people, animals, sounds, and environments in a positive way. This helps prevent fear and aggression later in life.\n\nFor cats, training focuses on litter box use, scratching appropriate surfaces, and interactive play. Use treats and praise to reinforce good behavior. Provide alternatives to unwanted behaviors – if your cat scratches furniture, offer attractive scratching posts.\n\nAddress problem behaviors promptly. Barking, jumping, or destructive behavior often stems from boredom, anxiety, or lack of exercise. Increase physical activity and mental stimulation. If problems persist, consult a professional trainer or behaviorist.\n\nPatience is essential. Every pet learns at their own pace. Celebrate small victories and remember that building a strong bond takes time and consistent effort.",
                'category' => 'Cats',
            ],
            [
                'title' => 'Preparing for Pet Emergencies',
                'content' => "Being prepared for pet emergencies can save your companion's life. Every pet owner should know basic first aid and have an emergency plan.\n\nCreate a pet first aid kit. Include gauze, adhesive tape, scissors, tweezers, a digital thermometer, hydrogen peroxide (to induce vomiting if instructed by a vet), and a pet first aid manual. Keep your veterinarian's contact information and the nearest emergency vet clinic's number readily available.\n\nKnow the signs of common emergencies. Difficulty breathing, severe bleeding, seizures, inability to urinate, suspected poisoning, and trauma from accidents require immediate veterinary attention. Don't wait to see if symptoms improve.\n\nLearn basic first aid techniques. Know how to perform CPR on your pet, apply pressure to stop bleeding, and safely transport an injured animal. Many organizations offer pet first aid courses.\n\nKeep your pet's medical records accessible. In an emergency, having vaccination records, medication lists, and medical history can help veterinarians provide appropriate care quickly.\n\nHave a disaster preparedness plan. In case of natural disasters or evacuation, have a pet emergency kit ready with food, water, medications, medical records, and comfort items. Know which hotels or shelters accept pets.\n\nConsider pet insurance. While not necessary for everyone, it can help cover unexpected emergency veterinary costs, which can be substantial.\n\nStay calm during emergencies. Your pet can sense your anxiety. Speak in a soothing voice and handle them gently. Quick, calm action and immediate veterinary care give your pet the best chance of recovery.",
                'category' => 'Other animal',
            ],
            [
                'title' => 'Grooming Tips for a Healthy Pet',
                'content' => "Regular grooming is essential for your pet's health and well-being. It's not just about keeping them looking good – grooming helps prevent health issues and strengthens your bond.\n\nFor dogs, brushing frequency depends on coat type. Long-haired breeds need daily brushing to prevent mats and tangles, while short-haired dogs can be brushed weekly. Regular brushing removes loose fur, distributes natural oils, and allows you to check for skin issues or parasites.\n\nBathing should be done as needed, typically every 4-8 weeks for dogs. Over-bathing can strip natural oils and cause dry skin. Use pet-specific shampoos – human products can irritate their skin. Always rinse thoroughly to remove all soap residue.\n\nNail trimming is crucial but often overlooked. Long nails can cause discomfort and affect your pet's gait. Trim nails every 3-4 weeks, or when you hear them clicking on the floor. If you're nervous about cutting too short, ask your vet or groomer to demonstrate.\n\nDental care is vital for overall health. Brush your pet's teeth regularly with pet-safe toothpaste. Dental disease can lead to serious health problems affecting the heart, liver, and kidneys. Provide dental chews and toys to help keep teeth clean.\n\nEar cleaning prevents infections, especially in dogs with floppy ears. Check ears weekly for redness, odor, or discharge. Clean with a vet-approved solution, never inserting anything deep into the ear canal.\n\nFor cats, regular brushing reduces hairballs and keeps their coat healthy. Most cats are excellent self-groomers, but they still benefit from your help, especially long-haired breeds.\n\nMake grooming a positive experience with treats and praise. Start young to help pets become comfortable with handling. If grooming becomes stressful or you're unsure about any aspect, professional groomers can help maintain your pet's coat and health.",
                'category' => 'General',
            ],
            [
                'title' => 'Understanding Dog Body Language',
                'content' => "Dogs communicate primarily through body language. Learning to read these signals helps you understand your dog's emotions and prevents misunderstandings.\n\nTail wagging doesn't always mean happiness. The position and speed matter. A high, stiff wag can indicate alertness or potential aggression. A low, slow wag suggests uncertainty. A relaxed, mid-level wag with loose body movements typically shows friendliness.\n\nEar position reveals much about mood. Forward-facing ears show interest and attention. Ears pulled back against the head indicate fear or submission. Relaxed ears in their natural position suggest contentment.\n\nEye contact has different meanings. Soft eyes with relaxed facial muscles show trust and affection. Hard stares with tense body posture can be a challenge or threat. If a dog looks away or shows the whites of their eyes (whale eye), they're likely stressed or uncomfortable.\n\nBody posture tells the whole story. A play bow – front end down, rear up – is an invitation to play. A dog making themselves smaller, with lowered body and tucked tail, is showing submission or fear. Stiff, upright posture with raised hackles indicates arousal, which could be excitement or aggression.\n\nMouth and facial expressions are important too. A relaxed, slightly open mouth is normal. Lip licking, yawning, or showing teeth can indicate stress or discomfort. A tense, closed mouth often accompanies anxiety.\n\nPaw lifting can mean uncertainty or anticipation. Some dogs lift a paw when pointing at something interesting, while others do it when anxious.\n\nUnderstanding these signals helps you respond appropriately to your dog's needs. If you notice stress signals, remove your dog from the situation. Recognizing play signals helps you engage in fun activities. Reading body language strengthens your relationship and keeps everyone safe.",
                'category' => 'Dogs',
            ],
            [
                'title' => 'Indoor Enrichment Activities for Cats',
                'content' => "Indoor cats need mental and physical stimulation to stay healthy and happy. Enrichment prevents boredom, reduces behavioral problems, and keeps your cat engaged.\n\nInteractive play is essential. Use wand toys to mimic prey movements – birds, mice, or insects. Play sessions should be 10-15 minutes, twice daily. Let your cat 'catch' the toy occasionally to satisfy their hunting instinct. Rotate toys to maintain interest.\n\nPuzzle feeders make mealtime engaging. Instead of a bowl, use food puzzles that require your cat to work for their meals. This provides mental stimulation and slows down fast eaters. Start with easy puzzles and gradually increase difficulty.\n\nVertical space is crucial for cats. Install cat trees, shelves, or window perches. Cats feel secure when they can observe from high vantage points. Create pathways along walls using shelves, allowing your cat to navigate the room without touching the floor.\n\nWindow watching provides endless entertainment. Set up bird feeders outside windows to create 'cat TV.' Secure window perches give your cat a comfortable viewing spot. Some cats enjoy videos made specifically for feline entertainment.\n\nScent enrichment engages their powerful sense of smell. Offer cat-safe herbs like catnip, silvervine, or cat grass. Hide treats around the house for scavenger hunts. Rotate toys through a closed container with catnip to refresh their appeal.\n\nScratch-friendly surfaces are necessary. Provide various scratching posts – vertical, horizontal, and angled. Use different materials like sisal, cardboard, and carpet. Place scratchers near sleeping areas and high-traffic zones.\n\nHiding spots make cats feel secure. Provide boxes, tunnels, or cat tents. Cats need places to retreat when they want privacy or feel overwhelmed.\n\nTraining sessions offer mental stimulation. Cats can learn tricks, come when called, and even walk on leashes. Use positive reinforcement with treats and praise. Short, fun sessions work best.\n\nConsider a companion if your cat seems lonely. Some cats thrive with a feline friend, though introductions must be gradual and careful.",
                'category' => 'Cats',
            ],
            [
                'title' => 'Choosing the Right Pet for Your Lifestyle',
                'content' => "Selecting a pet is a major decision that affects your life for years to come. The right match depends on your lifestyle, living situation, and personal preferences.\n\nConsider your activity level. High-energy dogs like Border Collies or Australian Shepherds need extensive daily exercise and mental stimulation. If you're active and outdoorsy, these breeds might be perfect. Prefer quiet evenings? Consider lower-energy breeds like Basset Hounds or senior pets who need less activity.\n\nLiving space matters. Large dogs can adapt to apartments with sufficient exercise, but small spaces work better for smaller breeds or cats. Consider outdoor access – do you have a yard, or will you need to walk your dog multiple times daily? Cats generally adapt well to various living situations.\n\nTime commitment varies by pet. Dogs require significant daily attention – feeding, walking, training, and companionship. Cats are more independent but still need daily interaction, play, and care. Small pets like rabbits or guinea pigs need daily care and regular habitat cleaning. Consider your work schedule and social life.\n\nFinancial responsibility is significant. Budget for food, routine veterinary care, vaccinations, preventive medications, grooming, and emergency medical expenses. Pet insurance can help with unexpected costs. Some breeds have specific health issues requiring extra care.\n\nAllergies affect pet choice. Some people tolerate certain breeds better than others. Spend time with the type of pet you're considering before committing. No pet is truly hypoallergenic, but some produce fewer allergens.\n\nFamily dynamics matter. Young children do well with patient, gentle pets. Consider everyone's comfort level and ability to help with pet care. Teach children appropriate interaction with animals.\n\nFuture plans should be considered. Pets live many years – will your lifestyle accommodate them long-term? Consider career changes, potential moves, or family planning.\n\nAdoption is wonderful. Shelters have pets of all ages, sizes, and temperaments. Adult pets often come trained and their personalities are known. Senior pets make excellent companions and deserve loving homes.\n\nResearch breeds or species thoroughly. Understand typical behaviors, needs, and potential challenges. Talk to current owners, veterinarians, and shelter staff. The right pet enriches your life immeasurably – take time to choose wisely.",
                'category' => 'General',
            ],
            [
                'title' => 'Common Health Issues in Dogs and Prevention',
                'content' => "Understanding common canine health issues helps you recognize problems early and take preventive measures. Regular veterinary care is essential, but awareness empowers you to be proactive.\n\nObesity affects over half of dogs. Excess weight leads to diabetes, joint problems, heart disease, and shortened lifespan. Prevent obesity through portion control, measured meals, limited treats, and regular exercise. If your dog is overweight, consult your vet for a safe weight loss plan.\n\nDental disease is extremely common. By age three, most dogs show signs of periodontal disease. Bacteria from infected gums can spread to vital organs. Prevent dental issues with regular brushing, dental chews, and professional cleanings. Watch for bad breath, difficulty eating, or swollen gums.\n\nEar infections plague dogs with floppy ears or those who swim frequently. Signs include head shaking, scratching, odor, or discharge. Keep ears clean and dry. After swimming or bathing, dry ears thoroughly. Regular checks catch infections early.\n\nSkin allergies cause intense itching and discomfort. Environmental allergens, food sensitivities, or flea bites trigger reactions. Symptoms include scratching, licking, red skin, or hair loss. Identify and avoid triggers when possible. Your vet can recommend treatments for relief.\n\nArthritis affects many older dogs and some younger ones with joint issues. Signs include stiffness, difficulty rising, reluctance to jump or climb stairs, and decreased activity. Maintain healthy weight to reduce joint stress. Supplements, medications, and physical therapy can help manage pain.\n\nHeartworm is preventable but potentially fatal. Transmitted by mosquitoes, heartworms damage the heart and lungs. Prevention is simple – monthly medication year-round. Annual testing ensures your dog remains heartworm-free.\n\nParasites like fleas, ticks, and intestinal worms cause various problems. Fleas trigger allergies and transmit diseases. Ticks carry Lyme disease and other illnesses. Intestinal parasites affect digestion and overall health. Use preventive medications and maintain good hygiene.\n\nKennel cough spreads easily in social settings. This respiratory infection causes persistent coughing. Vaccination helps prevent it, especially important for dogs who interact with others.\n\nRegular veterinary check-ups catch problems early. Annual exams for young dogs, twice yearly for seniors. Don't wait for obvious illness – preventive care is key to long, healthy life.",
                'category' => 'Dogs',
            ],
            [
                'title' => 'Caring for Exotic Pets: Birds, Rabbits, and Small Animals',
                'content' => "Exotic pets have unique needs that differ significantly from cats and dogs. Understanding these requirements ensures your small companion thrives.\n\nBirds are intelligent, social creatures requiring substantial care. They need spacious cages allowing full wing extension and flight. Provide varied perches of different diameters and textures for foot health. Mental stimulation is crucial – offer toys, foraging opportunities, and daily out-of-cage time in a safe, supervised area. Birds are messy and noisy, requiring daily cage cleaning. Diet varies by species but typically includes pellets, fresh vegetables, fruits, and limited seeds. Avoid toxic foods like avocado, chocolate, and caffeine. Birds bond strongly with owners and need daily interaction. Many live 20+ years, requiring long-term commitment.\n\nRabbits are not low-maintenance starter pets. They need large living spaces – minimum 12 square feet, plus exercise time. House rabbits should be litter trained and have bunny-proofed areas to explore. Diet consists mainly of hay (80%), with fresh vegetables and limited pellets. Avoid feeding too many fruits or treats. Rabbits need hiding spots and elevated platforms. They're social and often do better in bonded pairs. Spaying/neutering reduces aggression and health issues. Rabbits require regular grooming, especially long-haired breeds. Dental care is critical – teeth grow continuously and need wearing down through proper diet. Veterinary care from exotic pet specialists is essential. Rabbits can live 8-12 years with proper care.\n\nGuinea pigs are social and should be kept in same-sex pairs or groups. They need large cages with solid flooring, not wire. Provide hiding spots and enrichment. Diet requires unlimited hay, fresh vegetables daily, and vitamin C supplementation – guinea pigs can't produce their own. They're vocal and interactive, making various sounds. Regular nail trims and occasional baths keep them healthy. Guinea pigs live 5-7 years.\n\nHamsters are nocturnal and solitary (except dwarf varieties). They need appropriate-sized cages with deep bedding for burrowing, exercise wheels, and toys. Avoid cedar or pine shavings. Diet includes pellets, small amounts of fresh foods, and occasional treats. Handle gently and regularly for socialization. Hamsters live 2-3 years.\n\nAll exotic pets need specialized veterinary care. Find a vet experienced with your pet's species before emergencies arise. Research thoroughly before acquiring any exotic pet – their needs are complex and specific.",
                'category' => 'Other animal',
            ],
        ];

        // Array of placeholder images from picsum.photos (free placeholder service)
        $placeholderImages = [
            'https://picsum.photos/seed/article1/800/600',
            'https://picsum.photos/seed/article2/800/600',
            'https://picsum.photos/seed/article3/800/600',
            'https://picsum.photos/seed/article4/800/600',
            'https://picsum.photos/seed/article5/800/600',
            'https://picsum.photos/seed/article6/800/600',
            'https://picsum.photos/seed/article7/800/600',
            'https://picsum.photos/seed/article8/800/600',
            'https://picsum.photos/seed/article9/800/600',
            'https://picsum.photos/seed/article10/800/600',
            'https://picsum.photos/seed/article11/800/600',
            'https://picsum.photos/seed/article12/800/600',
            'https://picsum.photos/seed/article13/800/600',
        ];

        foreach ($articles as $index => $articleData) {
            // Find category by name
            $category = $categories->firstWhere('name', $articleData['category']);
            
            // Download and save image
            $featuredImage = null;
            if (isset($placeholderImages[$index])) {
                try {
                    $imageUrl = $placeholderImages[$index];
                    $imageContent = Http::timeout(10)->get($imageUrl)->body();
                    $filename = 'articles/article-' . ($index + 1) . '-' . time() . '.jpg';
                    Storage::disk('public')->put($filename, $imageContent);
                    $featuredImage = $filename;
                    $this->command->info("Downloaded image for: {$articleData['title']}");
                } catch (\Exception $e) {
                    $this->command->warn("Failed to download image for: {$articleData['title']}");
                }
            }
            
            Article::create([
                'author_id' => $adminUsers->random()->id,
                'category_id' => $category?->id,
                'title' => $articleData['title'],
                'content' => $articleData['content'],
                'featured_image' => $featuredImage,
                'views' => rand(50, 500),
            ]);
        }

        $this->command->info('Articles seeded successfully!');
    }
}
